"""Declarative base and shared column mixins for all ORM models."""

from datetime import datetime

from sqlalchemy import DateTime, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Root of the ORM hierarchy. Alembic reads Base.metadata to detect schema changes."""


class TimestampMixin:
    """Adds created_at / updated_at to a table.

    Timestamps are generated by PostgreSQL (server_default / onupdate), not by
    Python, so they stay correct even when rows are written outside the app.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )