"""trip icon and colour

Revision ID: 04834a6da96f
Revises: 600ebaa55703
Create Date: 2026-07-26 14:17:09.632785

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04834a6da96f"
down_revision: str | Sequence[str] | None = "600ebaa55703"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trips", sa.Column("icon", sa.String(length=30), nullable=True))
    op.add_column("trips", sa.Column("color", sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trips", "color")
    op.drop_column("trips", "icon")
    # ### end Alembic commands ###
