"""remember past trip members

Revision ID: 281bb7336687
Revises: c8b3a7f4e1d2
Create Date: 2026-07-26 10:37:07.486545

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "281bb7336687"
down_revision: str | Sequence[str] | None = "c8b3a7f4e1d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trip_past_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "MEMBER", name="memberrole", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "left_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trip_id", "user_id", name="uq_trip_past_member"),
    )
    op.create_index(
        op.f("ix_trip_past_members_trip_id"), "trip_past_members", ["trip_id"], unique=False
    )
    op.create_index(
        op.f("ix_trip_past_members_user_id"), "trip_past_members", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trip_past_members_user_id"), table_name="trip_past_members")
    op.drop_index(op.f("ix_trip_past_members_trip_id"), table_name="trip_past_members")
    op.drop_table("trip_past_members")
    # ### end Alembic commands ###
