"""add joined_at to trip members

Revision ID: 34eda0305cd5
Revises: 15d0737bcd43
Create Date: 2026-07-25 13:52:47.324248

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34eda0305cd5"
down_revision: str | Sequence[str] | None = "15d0737bcd43"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trip_members",
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trip_members", "joined_at")
    # ### end Alembic commands ###
