"""one owner per trip

Revision ID: 4e89faa55a64
Revises: 2bcfb49183a7
Create Date: 2026-08-19 17:27:09.613735

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e89faa55a64"
down_revision: str | Sequence[str] | None = "2bcfb49183a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_trip_single_owner",
        "trip_members",
        ["trip_id"],
        unique=True,
        postgresql_where=sa.text("role = 'OWNER'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_trip_single_owner",
        table_name="trip_members",
        postgresql_where=sa.text("role = 'OWNER'"),
    )
    # ### end Alembic commands ###
