"""multiple assignees per item

Revision ID: 5a859d92c002
Revises: df6b4562b9d9
Create Date: 2026-07-25 21:05:35.566931

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5a859d92c002"
down_revision: str | Sequence[str] | None = "df6b4562b9d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
