"""map pins and member locations

Revision ID: 600ebaa55703
Revises: 281bb7336687
Create Date: 2026-07-26 12:39:41.988783

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "600ebaa55703"
down_revision: str | Sequence[str] | None = "281bb7336687"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "map_pins",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "LODGING",
                "FOOD",
                "MEETING_POINT",
                "PARKING",
                "SIGHT",
                "OTHER",
                name="pincategory",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("latitude >= -90 AND latitude <= 90", name="ck_pin_latitude"),
        sa.CheckConstraint("longitude >= -180 AND longitude <= 180", name="ck_pin_longitude"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_map_pins_trip_id"), "map_pins", ["trip_id"], unique=False)
    op.create_table(
        "member_locations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("accuracy_m", sa.Float(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("latitude >= -90 AND latitude <= 90", name="ck_location_latitude"),
        sa.CheckConstraint("longitude >= -180 AND longitude <= 180", name="ck_location_longitude"),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trip_id", "user_id", name="uq_member_location"),
    )
    op.create_index(
        op.f("ix_member_locations_trip_id"), "member_locations", ["trip_id"], unique=False
    )
    op.create_index(
        op.f("ix_member_locations_user_id"), "member_locations", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_member_locations_user_id"), table_name="member_locations")
    op.drop_index(op.f("ix_member_locations_trip_id"), table_name="member_locations")
    op.drop_table("member_locations")
    op.drop_index(op.f("ix_map_pins_trip_id"), table_name="map_pins")
    op.drop_table("map_pins")
    # ### end Alembic commands ###
