"""multiple assignees per item

Revision ID: df6b4562b9d9
Revises: 34eda0305cd5
Create Date: 2026-07-25 21:02:06.154907

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df6b4562b9d9"
down_revision: str | Sequence[str] | None = "34eda0305cd5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item_assignees",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_id", "user_id", name="uq_item_assignee"),
    )
    op.create_index(op.f("ix_item_assignees_item_id"), "item_assignees", ["item_id"], unique=False)
    op.create_index(op.f("ix_item_assignees_user_id"), "item_assignees", ["user_id"], unique=False)
    op.drop_index(op.f("ix_items_assigned_to"), table_name="items")
    op.drop_constraint(op.f("items_assigned_to_fkey"), "items", type_="foreignkey")
    op.drop_column("items", "assigned_to")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("assigned_to", sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        op.f("items_assigned_to_fkey"),
        "items",
        "users",
        ["assigned_to"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(op.f("ix_items_assigned_to"), "items", ["assigned_to"], unique=False)
    op.drop_index(op.f("ix_item_assignees_user_id"), table_name="item_assignees")
    op.drop_index(op.f("ix_item_assignees_item_id"), table_name="item_assignees")
    op.drop_table("item_assignees")
    # ### end Alembic commands ###
